import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getAdminUser, teacherScope } from '@/lib/permissions';

export async function GET(request: NextRequest) {
  const payload = await getAdminUser(request);
  if (!payload) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const scope = teacherScope(payload);

  const questions = await prisma.question.findMany({
    where: scope ? { teacher_id: scope } : {},
    include: {
      testCases: { orderBy: { order_index: 'asc' } },
      subject: true,
    },
    orderBy: { created_at: 'desc' }
  });

  const subjects = await prisma.subject.findMany();
  
  return NextResponse.json({ questions, subjects });
}

export async function POST(request: NextRequest) {
  const payload = await getAdminUser(request);
  if (!payload) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json();
  const { action } = body;

  if (action === 'create') {
    const { title, topic, description, input_format, output_format, constraints, sample_input, sample_output, explanation, marks, difficulty, subject_name } = body;
    
    // Process Subject by Name
    let subject_id = body.subject_id;
    if (subject_name) {
      let subj = await prisma.subject.findFirst({ where: { name: subject_name } });
      if (!subj) {
        subj = await prisma.subject.create({ 
          data: { name: subject_name, code: subject_name.toUpperCase().replace(/[^A-Z0-9]/g, '_') } 
        });
      }
      subject_id = subj.id;
    }

    if (!title || !description || !subject_id) {
      return NextResponse.json({ error: 'title, description, and subject are required' }, { status: 400 });
    }

    // Assign the created question to the current admin
    const teacher_id = payload.user_id;
    const slug = `${title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-')}-${Date.now()}`;

    const question = await prisma.question.create({
      data: {
        title,
        slug,
        description,
        subject_id,
        teacher_id,
        topic: topic || null,
        difficulty: difficulty || 'MEDIUM',
        marks: parseInt(marks) || 10,
        input_format: input_format || null,
        output_format: output_format || null,
        constraints: constraints || null,
        sample_input: sample_input || null,
        sample_output: sample_output || null,
        explanation: explanation || null,
      }
    });
    return NextResponse.json({ success: true, question });
  }

  if (action === 'update') {
    const { id, title, topic, description, input_format, output_format, constraints, sample_input, sample_output, explanation, marks, difficulty } = body;
    
    // Verify ownership
    const q = await prisma.question.findUnique({ where: { id } });
    if (!q || q.teacher_id !== payload.user_id) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    await prisma.question.update({
      where: { id },
      data: {
        title,
        topic: topic || null,
        description,
        input_format: input_format || null,
        output_format: output_format || null,
        constraints: constraints || null,
        sample_input: sample_input || null,
        sample_output: sample_output || null,
        explanation: explanation || null,
        marks: parseInt(marks) || 10,
        difficulty: difficulty || 'MEDIUM',
      }
    });
    return NextResponse.json({ success: true });
  }

  if (action === 'generate_ai') {
    const { prompt, subject_name } = body;
    let title = "AI Generated Question";
    let description = "Description generated by AI based on: " + prompt;
    let constraints = "1 <= N <= 10^5\nTime Limit: 1.0s";
    let topic = "Data Structures";

    try {
      if (!process.env.AZURE_OPENAI_API_KEY || !process.env.AZURE_OPENAI_ENDPOINT || !process.env.AZURE_OPENAI_DEPLOYMENT) {
        return NextResponse.json({ error: 'Azure OpenAI configuration is missing in .env.local' }, { status: 500 });
      }
      
      const endpoint = `${process.env.AZURE_OPENAI_ENDPOINT}/openai/deployments/${process.env.AZURE_OPENAI_DEPLOYMENT}/chat/completions?api-version=2024-02-15-preview`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'api-key': process.env.AZURE_OPENAI_API_KEY,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          messages: [
            { role: 'system', content: 'You are a helpful assistant that generates programming questions.' },
            { role: 'user', content: `Generate a programming question based on this prompt: "${prompt}". Return ONLY a JSON object with these keys: "title", "topic", "description" (markdown), "constraints" (markdown). Do NOT include markdown blocks around the JSON.` }
          ],
          response_format: { type: 'json_object' }
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Azure OpenAI error:', errorText);
        return NextResponse.json({ error: 'Azure OpenAI API error' }, { status: 500 });
      }

      const responseData = await response.json();
      const text = responseData.choices[0].message.content || "{}";
      const json = JSON.parse(text.replace(/```json/g, '').replace(/```/g, '').trim());
      title = json.title || title;
      description = json.description || description;
      constraints = json.constraints || constraints;
      topic = json.topic || topic;
    } catch (e) {
      console.error('AI Generation error:', e);
    }

    let subject_id = body.subject_id;
    if (subject_name) {
      let subj = await prisma.subject.findFirst({ where: { name: subject_name } });
      if (!subj) {
        subj = await prisma.subject.create({ 
          data: { name: subject_name, code: subject_name.toUpperCase().replace(/[^A-Z0-9]/g, '_') } 
        });
      }
      subject_id = subj.id;
    }

    const slug = `${title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-')}-${Date.now()}`;

    const newQuestion = await prisma.question.create({
      data: {
        teacher_id: payload.user_id,
        subject_id: subject_id || 1, // fallback
        title,
        slug,
        topic,
        description,
        input_format: 'Standard Input',
        output_format: 'Standard Output',
        constraints,
        sample_input: '',
        sample_output: '',
        marks: 10,
        difficulty: 'MEDIUM',
      }
    });

    return NextResponse.json({ success: true, question: newQuestion });
  }

  if (action === 'delete') {
    const { id } = body;
    const q = await prisma.question.findUnique({ where: { id } });
    if (!q || q.teacher_id !== payload.user_id) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }
    await prisma.testCase.deleteMany({ where: { question_id: id } });
    await prisma.question.delete({ where: { id } });
    return NextResponse.json({ success: true });
  }

  if (action === 'add_test_case') {
    const { question_id, input, expected_output, is_hidden, marks } = body;
    const count = await prisma.testCase.count({ where: { question_id } });
    await prisma.testCase.create({
      data: {
        question_id,
        input,
        expected_output,
        is_hidden: is_hidden || false,
        marks: parseInt(marks) || 1,
        order_index: count,
      }
    });
    return NextResponse.json({ success: true });
  }

  if (action === 'delete_test_case') {
    await prisma.testCase.delete({ where: { id: body.id } });
    return NextResponse.json({ success: true });
  }

  return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
}
